### ISSUE TITLE
Day 1: Motivation: Read 1 & 2

### ISSUE THREAD

**Issue by theTechie** [theTechie/100DaysofMLCode#1]
https://waitbutwhy.com/2015/01/artificial-intelligence-revolution-1.html

https://waitbutwhy.com/2015/01/artificial-intelligence-revolution-2.html

**Comment by theTechie** [comment]
### Part 1
> **“AI has by now succeeded in doing essentially everything that requires ‘thinking’ but has failed to do most of what people and animals do ‘without thinking.'”**

## Law of Accelerating Returns

![projections](https://user-images.githubusercontent.com/1046486/42398340-1f5fc410-8187-11e8-85bc-93cd5f529c2c.png)


## Genetic Algorithms

![flappy_06](https://user-images.githubusercontent.com/1046486/42398635-3c3a3bb4-8188-11e8-9813-32f039513df0.png)


## Intelligence Explosion

![intelligence2](https://user-images.githubusercontent.com/1046486/42398547-dc504608-8187-11e8-9947-53c40b103dda.png)

**Comment by gagso** [comment]
![staircase1-586x600](https://user-images.githubusercontent.com/9055403/42680940-06fbfb24-86a4-11e8-80f5-072aff09b3a4.png)

![staircase2-600x510](https://user-images.githubusercontent.com/9055403/42680978-1efbf44a-86a4-11e8-8de9-6c0c7db6510b.png)

![tripwire-600x494](https://user-images.githubusercontent.com/9055403/42680992-232c8c82-86a4-11e8-9718-85de6d2fb74d.png)

![howard-graph-1024x629](https://user-images.githubusercontent.com/9055403/42681007-2aadc660-86a4-11e8-998d-c9001fdd7ad6.png)

![timeline-1024x534](https://user-images.githubusercontent.com/9055403/42681020-30669730-86a4-11e8-98a8-7d181bf52d90.png)

![square32-1024x1012](https://user-images.githubusercontent.com/9055403/42681028-34578fd4-86a4-11e8-9952-74dcb32ba4ce.jpg)

![existential-risk-chart-600x600](https://user-images.githubusercontent.com/9055403/42681035-3a49b818-86a4-11e8-8575-a5916ca00466.jpg)

![outcome-spectrum-600x408](https://user-images.githubusercontent.com/9055403/42681039-3d069738-86a4-11e8-9664-9243d6a6e15f.jpg)
